version: '2'
services:
  client:
    container_name: "client"
    image: extricator-ui:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - server
    depends_on:
      - server
    networks:
      - extricator-network

  server:
    container_name: "server"
    image: extricator-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    networks:
      - extricator-network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - "8080:8080"
    networks:
    - extricator-network

networks:
  extricator-network:
    driver: bridge